"use client";
import {useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,AudioLines,Database,FileCheck2,Activity} from 'lucide-react';
import {analyse,type Finding} from '@/lib/pump';
export default function FrontPage(){
 const [finding,setFinding]=useState<Finding>('none');
 const sample=useMemo(()=>analyse('suction',finding),[finding]);
 const hypothesis=sample.hypotheses.find(h=>h.id==='suction')!;
 return <main className="aqua-intro">
  <header className="intro-nav"><a className="intro-wordmark" href="/">AQUA<span>ASSET RELIABILITY</span></a><nav aria-label="Main navigation"><a href="#workflow">The workflow</a><a href="#evidence">Try the reasoning</a><a className="intro-launch" href="/desk">Open operations desk <ArrowUpRight size={17}/></a></nav></header>
  <section className="intro-hero"><div className="hero-copy"><p className="intro-kicker"><span/> BUILT FOR WATER OPERATIONS</p><h1>Every pump<br/>tells a story.<br/><em>Follow the evidence.</em></h1><p className="hero-description">An interactive agent that brings process trends, vibration and maintenance history into one investigation — and helps an engineer decide what to check next.</p><a className="intro-primary" href="/desk">Investigate pump P-101 <ArrowRight size={20}/></a><p className="intro-small">Working hackathon prototype · synthetic plant data</p></div><div className="hero-plate"><div className="plate-top"><span>FIELD NOTE / 001</span><span>P-101 · CENTRIFUGAL PUMP</span></div><p className="plate-question">Pressure is falling.<br/>Vibration is rising.<br/><span>What connects the two?</span></p><div className="plate-drawing"><img src="/pump-train.svg" alt="Suction line, strainer, centrifugal pump, motor and discharge line."/></div><div className="plate-readings"><div><span>SUCTION PRESSURE</span><strong>0.27 <small>bar(g)</small></strong></div><div><span>VIBRATION</span><strong>3.73 <small>mm/s RMS</small></strong></div></div><p className="plate-caption">A clue is a starting point.<br/>AQUA helps you test the explanation.</p><div className="plate-bottom"><span>SYNTHETIC SNAPSHOT</span><a href="/desk">Open this investigation <ArrowRight size={17}/></a></div></div></section>
  <section className="intro-thesis"><p className="intro-kicker">THE PROBLEM</p><h2>The alarm is in one system.<br/>The explanation is spread across three.</h2><p>A historian shows the operating change. A spectrum adds the mechanical clues. The work history supplies context. AQUA connects those sources around the asset already on your screen.</p></section>
  <section className="intro-sources" aria-label="Evidence sources"><article><Activity size={24}/><div><h3>Process evidence</h3><p>Pressure, flow, load and temperature at a matched operating speed.</p><span>SCADA-STYLE TELEMETRY</span></div></article><article><AudioLines size={24}/><div><h3>Vibration evidence</h3><p>Waveforms, frequency spectra and signal-quality checks before interpretation.</p><span>GENERATED SIGNALS + COMPUTED FFT</span></div></article><article><Database size={24}/><div><h3>Maintenance context</h3><p>Fictional work records and structured engineer inspection findings.</p><span>MAXIMO-STYLE RECORDS</span></div></article></section>
  <section className="intro-workflow" id="workflow"><div className="intro-section-title"><p className="intro-kicker">01 / THE WORKFLOW</p><h2>From observation<br/>to a reviewed next step.</h2><p>Ask a question in the context of the selected pump. See which tools the agent used, challenge the assessment, and approve the action yourself.</p></div><ol className="workflow-steps">{[
   ['Investigate','The model chooses evidence tools to read process trends, check vibration quality, retrieve maintenance context and compare hypotheses.'],
   ['Challenge','Add a structured inspection finding. The evidence, support ranking and next discriminating check change together.'],
   ['Review','Ask for an inspection proposal. Its scope and source references are visible, and the draft is tied to the current evidence revision.'],
   ['Approve & preserve','Only your approval saves the task. AQUA reads it back from the database and keeps it in your signed-in case history.'],
  ].map(([title,detail],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{detail}</p></div>{i===3?<FileCheck2 size={24}/>:<ArrowRight size={23}/>}</li>)}</ol></section>
  <section className="intro-evidence" id="evidence"><div className="intro-section-title"><p className="intro-kicker">02 / EVIDENCE CAN CHANGE THE ANSWER</p><h2>Challenge the<br/>first explanation.</h2><p>Try a finding below. This preview runs the same deterministic analysis as the operations desk. The scores illustrate the reasoning process; they are not failure probabilities.</p><div className="evidence-switch" role="group" aria-label="Example inspection finding">{[{id:'none',label:'Before inspection'},{id:'clear',label:'Suction path is clear'},{id:'loose-sensor',label:'Sensor mounting is loose'}].map(x=><button key={x.id} aria-pressed={finding===x.id} onClick={()=>setFinding(x.id as Finding)}>{finding===x.id&&<Check size={15}/>} {x.label}</button>)}</div></div><div className="example-case" aria-live="polite"><div className="example-heading"><span>P-101 / EVIDENCE PREVIEW</span><span>{finding==='none'?'INITIAL VIEW':'NEW FINDING'}</span></div><p className="intro-kicker">{sample.quality?'MEASUREMENT QUALITY':'WORKING HYPOTHESIS'}</p><h3>{sample.quality?'Validate the sensor first.':hypothesis.title}</h3>{sample.quality?<div className="example-quality">Vibration features withheld<small>A questionable measurement cannot support a mechanical diagnosis.</small></div>:<div className="example-support"><strong>{hypothesis.support}<small>/ 100</small></strong><span>illustrative support</span><div><i style={{width:hypothesis.support+'%'}}/></div></div>}<div className="example-check"><span>NEXT DISCRIMINATING CHECK</span><p>{sample.quality?sample.hypotheses[0].check:hypothesis.check}</p></div><p className="example-limits">{sample.quality?'Checking the sensor does not establish that the pump is healthy.':hypothesis.against}</p><a href="/desk">Explore the full evidence <ArrowRight size={17}/></a></div></section>
  <section className="intro-boundaries"><div><p className="intro-kicker">03 / WHAT IS BUILT</p><h2>A working process.<br/>Clear engineering limits.</h2></div><div className="boundary-columns"><article><h3>Implemented in the demo</h3><ul><li>Five repeatable synthetic pump scenarios</li><li>OpenRouter agent with six evidence tools</li><li>Trends, waveform, spectrum and illustrative FMEA</li><li>Evidence revision, approval and persistent tasks</li><li>Optional browser voice input and read-aloud</li></ul></article><article><h3>Outside this prototype</h3><ul><li>Live SCADA or Maximo integration</li><li>Equipment control or automatic work orders</li><li>Validated remaining-life or failure-date predictions</li><li>Confirmed root cause or calculated NPSH margin</li><li>Hermes or Ambiguous AI integration</li></ul></article></div></section>
  <section className="intro-ending"><p className="intro-kicker">AQUA / SIGNALSPROUT</p><h2>See the evidence.<br/>Ask the next question.</h2><a className="intro-primary" href="/desk">Enter the operations desk <ArrowRight size={20}/></a><p>Created for AI Tinkerers’ Agents, Everywhere hackathon.</p></section>
  <footer className="intro-footer"><span>AQUA · PUMP RELIABILITY OPERATIONS DESK</span><a href="https://www.figma.com/design/mMb88S1Lu81xu80SW13P7O?node-id=2-180" target="_blank" rel="noreferrer">Designed in Figma <ArrowUpRight size={14}/></a><span>SYNTHETIC DATA / ENGINEER IN CONTROL</span></footer>
 </main>;
}

