"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ArrowRight,Check,ChevronRight,ClipboardCheck,Database,Download,Droplets,FileText,Gauge,History,Layers,MessageSquare,Plus,Send,Settings2,ShieldCheck,Sparkles,Waves,X} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,AreaChart,Area,ReferenceLine,BarChart,Bar} from 'recharts';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {analyse,scenarios,findings,type Scenario,type Finding,type Evidence} from '@/lib/pump';

type Event={id:string,kind:string,created:string,body:{finding?:Finding,note?:string,title?:string,status?:string}};
type Message={role:'assistant'|'user',content:string,mode?:string};
const tip={contentStyle:{background:'#182b35',border:'1px solid #35505d',borderRadius:8,color:'#edf4f5',fontSize:12},labelStyle:{color:'#9fb6c3'}};
function Picker({value,onChange,items,label}:{value:string,onChange:(v:string)=>void,items:{id:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [scenario,setScenario]=useState<Scenario>('suction'),[finding,setFinding]=useState<Finding>('none'),[tab,setTab]=useState('overview'),[window,setWindow]=useState('24'),[signal,setSignal]=useState('vibration'),[waveTab,setWaveTab]=useState('spectrum');
 const result=useMemo(()=>analyse(scenario,finding),[scenario,finding]);const lead=result.hypotheses[0];
 const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('guided'),[chatError,setChatError]=useState('');
 const [events,setEvents]=useState<Event[]>([]),[storageError,setStorageError]=useState(''),[loading,setLoading]=useState(true),[saveBusy,setSaveBusy]=useState(false),[notice,setNotice]=useState('');
 const [evidence,setEvidence]=useState<Evidence|null>(null),[inspection,setInspection]=useState(false),[propose,setPropose]=useState(false),[settings,setSettings]=useState(false),[approved,setApproved]=useState(false),[draftFinding,setDraftFinding]=useState<Finding>('restriction'),[note,setNote]=useState(''),[taskTitle,setTaskTitle]=useState('');
 const chatEnd=useRef<HTMLDivElement>(null),generation=useRef(0),saveId=useRef('');
 const changeScenario=(s:Scenario)=>{generation.current++;setScenario(s);setFinding('none');setMessages([]);setChatError('');setNotice('');setInspection(false);setPropose(false);setEvidence(null);};
 useEffect(()=>{fetch('/api/copilot').then(r=>r.json() as Promise<{mode:string}>).then(d=>setMode(d.mode||'guided')).catch(()=>setMode('guided'));},[]);
 useEffect(()=>{let live=true;setLoading(true);setEvents([]);setStorageError('');fetch('/api/cases?scenario='+scenario).then(async r=>{const data=await r.json() as {error:string,events:Event[]};if(!r.ok)throw Error(data.error);if(live){setEvents(data.events);const last=data.events.filter((e:Event)=>e.kind==='finding').at(-1);if(last)setFinding(last.body.finding||'none');}}).catch(e=>{if(live)setStorageError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false};},[scenario]);
 useEffect(()=>{const box=chatEnd.current?.parentElement;if(box)box.scrollTop=box.scrollHeight;},[messages,busy]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_pump_investigation',description:'Read the selected synthetic pump evidence and ranked hypotheses. Does not save or control equipment.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {asset:'P-101',scenario,headline:result.headline,evidence:result.evidence,hypotheses:result.hypotheses};}},{name:'select_demo_scenario',description:'Select a synthetic scenario and reset the current unsaved conversation. No plant or external system changes.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:scenarios.map(s=>s.id)}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {scenario:Scenario};if(!x||Object.keys(x).length!==1||!scenarios.some(s=>s.id===x.scenario))throw Error('Invalid scenario');changeScenario(x.scenario);return {selected:x.scenario};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[scenario,result]);
 async function ask(text=question){if(!text.trim()||busy)return;const token=generation.current;setBusy(true);setChatError('');setQuestion('');const next=[...messages,{role:'user' as const,content:text}];setMessages(next);try{const r=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario,finding,question:text,history:messages})});const d=await r.json() as {error:string,reply:string,mode:string};if(!r.ok)throw Error(d.error);if(token===generation.current)setMessages([...next,{role:'assistant',content:d.reply,mode:d.mode}]);}catch(e){if(token===generation.current){setChatError((e as Error).message);setQuestion(text);}}finally{setBusy(false);}}
 async function save(kind:'task'|'finding'){if(saveBusy)return;setSaveBusy(true);setStorageError('');try{if(!saveId.current)saveId.current=crypto.randomUUID();const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saveId.current,scenario,kind,finding:kind==='finding'?draftFinding:finding,note,title:taskTitle,approved})});const d=await r.json() as {error:string,reply:string,mode:string};if(!r.ok)throw Error(d.error);const refreshed=await fetch('/api/cases?scenario='+scenario);const list=await refreshed.json() as {error:string,events:Event[]};if(!refreshed.ok)throw Error(list.error);setEvents(list.events);if(kind==='finding'){setFinding(draftFinding);generation.current++;setMessages([]);}setInspection(false);setPropose(false);setNotice(kind==='finding'?'Inspection saved. Hypotheses recalculated.':'Inspection approved and saved to the AQUA case.');saveId.current='';}catch(e){setStorageError((e as Error).message);}finally{setSaveBusy(false);}}
 function exportCase(){const content={title:'AQUA P-101 investigation',synthetic:true,scenario,exportedAt:new Date().toISOString(),evidence:result.evidence,hypotheses:result.hypotheses,events,limitations:['Illustrative ratings; not calibrated probabilities','Remaining life not modelled','External integrations not connected']};const blob=new Blob([JSON.stringify(content,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AQUA-P101-investigation.json';a.click();URL.revokeObjectURL(url);}
 const trend=result.trend.slice(-Number(window));const metrics=[{label:'Flow rate',value:result.now.flow.toFixed(0),unit:'m³/h',detail:`${((result.now.flow/result.base.flow-1)*100).toFixed(1)}% vs reference`,color:'mint'}, {label:'Suction pressure',value:result.now.suction.toFixed(2),unit:'bar(g)',detail:`${(result.now.suction-result.base.suction).toFixed(2)} bar vs reference`,color:scenario==='suction'?'amber':'mint'}, {label:'Vibration · DE radial',value:result.quality?'—':result.wave.rms.toFixed(2),unit:'mm/s RMS',detail:result.quality?'Measurement requires validation':'Calculated from current waveform',color:result.active?'amber':'mint'}, {label:'Bearing temperature',value:result.now.temp.toFixed(1),unit:'°C',detail:`${(result.now.temp-result.base.temp).toFixed(1)} °C vs reference`,color:result.now.temp>65?'amber':'mint'}];
 return <main className="deck"><header><div className="brand"><Droplets/> AQUA <span>/ RELIABILITY COMMAND</span></div><div className="header-actions"><span className="demo">SYNTHETIC DEMO</span><button className="icon-button" aria-label="Connection settings" onClick={()=>setSettings(true)}><Settings2 size={19}/></button><span className="avatar">SA</span></div></header>
 <section className="heading"><div><p className="eyebrow">WATER OPERATIONS <ChevronRight size={12}/> PUMP STATION 04</p><h1>P-101 <span>Main centrifugal pump</span></h1><p className="sub"><span className={'status '+(result.active?'amber':'mint')}>{result.active?'Investigation open':'Within demo baseline'}</span><span>1,500 rpm</span><span>Duty pump · 110 kW motor</span><span>12 Sep 2026 · 12:00 GST</span></p></div><div className="scenario-control"><label>SIMULATE A SCENARIO</label><Picker label="Simulation scenario" value={scenario} onChange={v=>changeScenario(v as Scenario)} items={[...scenarios]}/></div></section>
 <div className="metrics">{metrics.map(m=><article className="metric" key={m.label}><p>{m.label}<Activity size={15}/></p><strong>{m.value}<small>{m.unit}</small></strong><span className={m.color}>{m.detail}</span></article>)}</div>
 <div className="main-grid"><div className="workspace"><Tabs value={tab} onValueChange={setTab}><div className="workspace-nav"><TabsList variant="line"><TabsTrigger value="overview"><Gauge/> Overview</TabsTrigger><TabsTrigger value="vibration"><Waves/> Vibration</TabsTrigger><TabsTrigger value="fmea"><Layers/> FMEA</TabsTrigger><TabsTrigger value="lifecycle"><History/> Lifecycle</TabsTrigger></TabsList><button className="text-button" aria-label="Export case" onClick={exportCase}><Download size={15}/><span>Export case</span></button></div>
 <TabsContent value="overview"><section className="panel"><div className="panel-title"><h2><Activity size={18}/> Operating picture</h2><Picker label="Trend time window" value={window} onChange={setWindow} items={[{id:'24',label:'Last 24 hours'},{id:'48',label:'Last 48 hours'},{id:'72',label:'Last 72 hours'}]}/></div><div className="chart-controls"><Picker label="Trend signal" value={signal} onChange={setSignal} items={[{id:'vibration',label:'Overall vibration · mm/s RMS'},{id:'suction',label:'Suction pressure · bar(g)'},{id:'flow',label:'Flow rate · m³/h'},{id:'temp',label:'Bearing temperature · °C'}]}/><span>Hourly synthetic historian readings</span></div><div className="chart large-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:14,right:24,left:-8,bottom:2}}><defs><linearGradient id="mintArea" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6bdeca" stopOpacity={.24}/><stop offset="1" stopColor="#6bdeca" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#22343e" vertical={false}/><XAxis dataKey="hour" tickFormatter={v=>`−${72-Number(v)}h`} stroke="#7893a2" tickLine={false} axisLine={false} minTickGap={36}/><YAxis stroke="#7893a2" tickLine={false} axisLine={false} tickCount={4} domain={['auto','auto']} tickFormatter={v=>Number(v).toFixed(signal==='flow'?0:1)}/><Tooltip {...tip} labelFormatter={v=>`${72-Number(v)} hours before current snapshot`}/><Area type="monotone" dataKey={signal} stroke="#73ddcc" fill="url(#mintArea)" strokeWidth={2.5} connectNulls={false} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><div className="insight"><Activity size={20}/><div><b>{result.headline}</b><p>{result.quality?'Vibration data are unreliable. Validate the measurement chain before mechanical diagnosis.':result.active?lead.reason:'Stable process and waveform observations at matched rotational speed.'}</p></div></div></section>
 <section className="panel evidence-panel"><div className="panel-title"><h2><Database size={18}/> Evidence stream</h2><span>{result.evidence.length} SOURCES</span></div><div className="evidence-grid">{result.evidence.map(e=><button className="evidence-card" key={e.id} onClick={()=>setEvidence(e)}><div><span className="evidence-id">{e.id}</span><ArrowUpRight size={15}/></div><h3>{e.title}</h3><p>{e.source}</p><span className="read-evidence">Inspect evidence <ArrowRight size={13}/></span></button>)}</div></section></TabsContent>
 <TabsContent value="vibration"><section className="panel"><div className="panel-title"><h2><Waves size={18}/> Vibration lab</h2><span>DE · RADIAL</span></div><div className="lab-summary"><div><b>{result.quality?'Invalid':result.wave.rms.toFixed(2)}</b><span>Velocity RMS · mm/s</span></div><div><b>{result.wave.crest.toFixed(2)}</b><span>Crest factor</span></div><div><b>{result.wave.kurtosis.toFixed(2)}</b><span>Kurtosis</span></div><div><b>25 Hz</b><span>1× running speed</span></div></div><Tabs value={waveTab} onValueChange={setWaveTab}><TabsList className="lab-tabs"><TabsTrigger value="spectrum">Frequency spectrum</TabsTrigger><TabsTrigger value="waveform">Time waveform</TabsTrigger></TabsList><TabsContent value="spectrum"><div className="chart lab-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={result.wave.spectrum.filter(p=>p.hz<=800)} margin={{right:20,left:0,bottom:10}}><CartesianGrid stroke="#22343e" vertical={false}/><XAxis dataKey="hz" interval={99} stroke="#91a8b5" tickLine={false}/><YAxis stroke="#91a8b5" tickLine={false}/><Tooltip {...tip} labelFormatter={v=>`${v} Hz`}/><Bar dataKey="amplitude" fill="#77dfcd" isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="chart-note">Frequency (Hz) · velocity peak amplitude (mm/s) · Hann window, 1 Hz resolution</p></TabsContent><TabsContent value="waveform"><div className="chart lab-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={result.wave.samples.slice(0,512).map((v,i)=>({ms:i/result.wave.fs*1000,velocity:v}))}><CartesianGrid stroke="#22343e" vertical={false}/><XAxis dataKey="ms" tickFormatter={v=>Number(v).toFixed(0)} minTickGap={40} stroke="#91a8b5"/><YAxis stroke="#91a8b5"/><Tooltip {...tip} labelFormatter={v=>`${Number(v).toFixed(1)} ms`}/><Line dataKey="velocity" stroke="#77dfcd" strokeWidth={1.2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="chart-note">First 250 ms of the 1-second record · velocity (mm/s) · 2,048 samples/s</p></TabsContent></Tabs><div className="insight"><Waves size={20}/><div><b>{result.quality?'Do not interpret this channel':'A signature supports a hypothesis; it does not prove a cause.'}</b><p>{result.quality?'The signal is missing, flat or reported unreliable. Check the sensor first.':'Bearing race diagnosis requires bearing geometry and acceleration-envelope evidence. This demo uses a generated velocity waveform.'}</p></div></div></section></TabsContent>
 <TabsContent value="fmea"><section className="panel"><div className="panel-title"><h2><Layers size={18}/> Failure mode & effects register</h2><span>ENGINEER REVIEW</span></div><p className="section-note">Illustrative 1–10 severity, occurrence and detection ratings. Higher detection means harder to detect. RPN = S × O × D; these values are not calibrated risk probabilities.</p><Table><TableHeader><TableRow><TableHead>Failure mode</TableHead><TableHead>Effect</TableHead><TableHead>S / O / D</TableHead><TableHead>RPN</TableHead></TableRow></TableHeader><TableBody>{result.hypotheses.map(h=><TableRow key={h.id}><TableCell><strong>{h.title}</strong><div className="table-meta">Evidence support {h.support}/100</div></TableCell><TableCell className="effect-cell">{h.effect}</TableCell><TableCell className="numeric">{h.severity} / {h.occurrence} / {h.detection}</TableCell><TableCell><span className="rpn">{h.severity*h.occurrence*h.detection}</span></TableCell></TableRow>)}</TableBody></Table><div className="fmea-checks">{result.hypotheses.map(h=><article key={h.id}><h3>{h.title}</h3><p>{h.check}</p><div className="chips">{h.evidence.map(id=><button key={id} onClick={()=>setEvidence(result.evidence.find(e=>e.id===id)!)}>{id}</button>)}</div></article>)}</div></section></TabsContent>
 <TabsContent value="lifecycle"><section className="panel"><div className="panel-title"><h2><History size={18}/> Asset lifecycle</h2><span>P-101</span></div><div className="lab-summary lifecycle-metrics"><div><b>{result.efficiency.toFixed(1)}%</b><span>Wire-to-water efficiency</span></div><div><b>{result.head.toFixed(1)} m</b><span>Pressure-difference head</span></div><div><b>Not modelled</b><span>Remaining useful life</span></div></div><p className="section-note">Efficiency = flow × pressure difference ÷ electrical input. Assumes equal flange elevation and negligible velocity-head difference. This is overall electrical-to-hydraulic efficiency; shaft power is not available.</p><div className="timeline"><article><span>FEB 2021</span><div><h3>Commissioned into duty service</h3><p>110 kW motor · design flow 480 m³/h · synthetic asset record.</p></div></article><article><span>AUG 2026</span><div><h3>Routine lubrication inspection</h3><p>WO-2031 · lubricant condition recorded; no bearing replacement.</p></div></article>{scenario==='alignment'&&<article><span>11 SEP 2026</span><div><h3>Coupling replacement</h3><p>WO-2048 · alignment attachment missing. Verify the return-to-service evidence.</p></div></article>}<article><span>CURRENT</span><div><h3>{result.headline}</h3><p>Use the investigation to decide the next inspection. A root cause requires verification.</p></div></article>{events.map(e=><article key={e.id}><span>{new Date(e.created).toLocaleDateString('en-GB')}</span><div><h3>{e.kind==='task'?'Inspection approved':findings.find(f=>f.id===e.body.finding)?.label}</h3><p>{e.body.title||e.body.note||'Reported evidence saved to this case.'}</p><small>{e.kind==='task'?'AQUA demo task · no external work order issued':'Engineer-reported · synthetic case'}</small></div></article>)}</div></section></TabsContent>
 </Tabs>
 <section className="panel hypothesis-panel"><div className="panel-title"><h2><ShieldCheck size={18}/> Working hypotheses</h2><button className="text-button" onClick={()=>{setInspection(true);saveId.current='';setNote('');}}><Plus size={15}/> Add evidence</button></div><p className="section-note">Evidence support score · illustrative rules, not a probability of failure</p><div className="hypothesis-list">{result.hypotheses.map((h,i)=><article key={h.id} className={i===0&&result.active?'leading':''}><div className="rank">0{i+1}</div><div className="hypothesis-body"><div className="hypothesis-heading"><h3>{h.title}</h3><span>{h.support}<small>/100</small></span></div><div className="support-track"><div style={{width:h.support+'%'}}/></div><p>{i===0? h.against:h.reason}</p><div className="chips">{h.evidence.map(id=><button key={id} onClick={()=>setEvidence(result.evidence.find(e=>e.id===id)!)}>{id}</button>)}</div></div></article>)}</div></section>
 </div>
 <aside className="right-rail"><section className="panel agent-panel"><div className="panel-title"><h2><Sparkles size={18}/> Reliability copilot</h2><span className="agent-mode">{mode==='ai'?'AI CONNECTED':'GUIDED DEMO'}</span></div><div className="agent-context"><span>P-101</span><span>{result.evidence.length} evidence items</span><span>Read-only analysis</span></div><div className="conversation" aria-live="polite">{messages.length===0?<div className="agent-welcome"><div className="agent-orb"><Sparkles size={28}/></div><h3>Let’s investigate P-101.</h3><p>{mode==='ai'?'Ask a question across process, vibration and maintenance evidence.':'Explore the evidence with the guided investigation. Free-form AI needs an OpenRouter connection.'}</p><div className="suggestions">{['Why is vibration rising?','What should I inspect next?','Explain the FMEA','Can we estimate remaining life?'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div></div>:messages.map((m,i)=><div key={i} className={'message '+m.role}><span>{m.role==='user'?'YOU':m.mode==='ai'?'AQUA AI':'AQUA · GUIDED'}</span><p>{m.content}</p></div>)}{busy&&<div className="thinking"><Activity size={15}/> Reviewing the evidence…</div>}<div ref={chatEnd}/></div>{chatError&&<p role="alert" className="error">{chatError}</p>}<form className="chat-form" onSubmit={e=>{e.preventDefault();ask();}}><textarea aria-label="Ask the reliability copilot" placeholder="Ask about this pump…" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}}}/><button disabled={busy||!question.trim()} aria-label="Send question"><Send size={17}/></button></form><div className="agent-bottom"><ShieldCheck size={13}/> Hypotheses require engineer verification</div></section>
 <section className="panel next-action"><div className="panel-title"><h2><ClipboardCheck size={18}/> Next best check</h2></div><h3>{result.active?lead.title:'Maintain the baseline'}</h3><p>{result.active?lead.check:'Continue routine inspections and preserve matched-load reference waveforms.'}</p><button className="primary" onClick={()=>{setPropose(true);setApproved(false);setTaskTitle(result.active?lead.check:'Collect a matched-load reference waveform and review routine lubrication.');saveId.current='';}}>Create inspection <ArrowRight size={16}/></button><span className="caption">Review and approve before saving</span></section>
 <section className="source-status"><div><Database size={15}/><h3>Data connections</h3></div>{[['SCADA historian','Simulated'],['Vibration monitor','Simulated'],['Maximo maintenance','Simulated'],['Ambiguous AI','Not connected']].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}<button className="text-button" onClick={()=>setSettings(true)}>View connection status <ArrowUpRight size={14}/></button></section></aside></div>
 {notice&&<div className="notice" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <footer><span>AQUA / ASSET INTELLIGENCE</span><span>{loading?'Loading case history…':events.length+' saved case events'} · Synthetic data · No plant controls</span></footer>
 <Sheet open={!!evidence} onOpenChange={o=>{if(!o)setEvidence(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{evidence?.title}</SheetTitle><SheetDescription>{evidence?.id} · {evidence?.source}</SheetDescription></SheetHeader><div className="sheet-body"><p>{evidence?.detail}</p><h3>Quality & provenance</h3><p>{evidence?.quality}</p><h3>Interpretation boundary</h3><p>This item supports or challenges a hypothesis. Synthetic evidence demonstrates the process; it is not a validated prediction for a real pump.</p></div></SheetContent></Sheet>
 <Dialog open={inspection} onOpenChange={o=>{if(!saveBusy)setInspection(o);}}><DialogContent><DialogHeader><DialogTitle>Add inspection evidence</DialogTitle><DialogDescription>Record a reported observation for this synthetic P-101 case. The ranking will be recalculated.</DialogDescription></DialogHeader><label className="field-label">Inspection finding</label><Picker label="Inspection finding" value={draftFinding} onChange={v=>setDraftFinding(v as Finding)} items={findings}/><p className="muted-copy">{findings.find(f=>f.id===draftFinding)?.description}</p><label className="field-label" htmlFor="note">Engineer note (optional)</label><textarea id="note" className="field" placeholder="Record measurement, location and check performed…" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><p className="muted-copy">The selected finding updates the rules. Free-text notes are retained as context and are not automatically treated as proof.</p>{storageError&&<div className="error" role="alert">{storageError}{storageError.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in to save</a>}</div>}<button className="primary modal-primary" disabled={saveBusy} onClick={()=>save('finding')}>{saveBusy?'Saving…':'Save evidence & reassess'}</button></DialogContent></Dialog>
 <Dialog open={propose} onOpenChange={o=>{if(!saveBusy)setPropose(o);}}><DialogContent><DialogHeader><DialogTitle>Review proposed inspection</DialogTitle><DialogDescription>This creates an AQUA demo task for P-101. Ambiguous AI and Maximo are not connected.</DialogDescription></DialogHeader><label htmlFor="task" className="field-label">Inspection scope</label><textarea id="task" className="field" value={taskTitle} maxLength={500} onChange={e=>setTaskTitle(e.target.value)}/><div className="chips">{lead.evidence.map(id=><span key={id}>{id}</span>)}</div><label className="approval"><Checkbox checked={approved} onCheckedChange={v=>setApproved(v===true)}/>I have reviewed this inspection scope and approve saving the demo task.</label>{storageError&&<div className="error" role="alert">{storageError}{storageError.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in to save</a>}</div>}<button className="primary modal-primary" disabled={!approved||saveBusy||!taskTitle.trim()} onClick={()=>save('task')}>{saveBusy?'Saving…':'Approve & save inspection'}</button></DialogContent></Dialog>
 <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Connection status</SheetTitle><SheetDescription>The synthetic demonstration works without external accounts.</SheetDescription></SheetHeader><div className="sheet-body"><h3>OpenRouter · {mode==='ai'?'configured':'not connected'}</h3><p>{mode==='ai'?'AI answers use the same computed pump evidence shown in the deck.':'Guided replies use deterministic evidence rules. Connect a server-side OpenRouter key to enable free-form AI conversation.'}</p><h3>Ambiguous AI · not connected</h3><p>AQUA currently saves inspection evidence and approved tasks to its own case history. Shared Ambiguous documents and tasks are the next integration step after workspace access is configured.</p><a href="https://app.ambiguous.ai" target="_blank" rel="noreferrer" className="external-link">Open Ambiguous AI <ArrowUpRight size={15}/></a><h3>SCADA / Maximo / vibration</h3><p>All records are synthetic and labelled. No plant endpoint is connected, and no equipment command is available.</p><h3>Case history</h3><p>{storageError||'Inspection findings and approved tasks are saved to your signed-in case history.'}</p>{storageError.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top" className="external-link">Sign in to save cases</a>}</div></SheetContent></Sheet>
 </main>;
}

