"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Check,Download,Mic,Send,Settings2,Volume2,X,Plus,MessageSquare} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine,BarChart,Bar} from 'recharts';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {analyse,scenarios,findings,type Scenario,type Finding,type Evidence} from '@/lib/pump';
import {analysisRevision,proposalFor,type Proposal,type ToolTrace} from '@/lib/agent';

type CaseEvent={id:string;kind:string;created:string;body:{finding?:Finding;note?:string;title?:string;status?:string;evidence?:string[];teamsDelivery?:string}};
type Message={role:'assistant'|'user';content:string;mode?:string;trace?:ToolTrace[];proposal?:Proposal};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;onresult:((event:{results:{[key:number]:{[key:number]:{transcript:string}}}})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null};
const tip={contentStyle:{background:'#fff',border:'1px solid #ccd5d9',borderRadius:3,color:'#17252c',fontSize:14},labelStyle:{color:'#526570'}};
function Picker({value,onChange,items,label,disabled=false}:{value:string;onChange:(v:string)=>void;items:readonly {id:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select>}

export default function Home(){
 const [scenario,setScenario]=useState<Scenario>('suction'),[finding,setFinding]=useState<Finding>('none'),[tab,setTab]=useState('trends'),[hours,setHours]=useState('24'),[signal,setSignal]=useState('suction');
 const result=useMemo(()=>analyse(scenario,finding),[scenario,finding]),lead=result.hypotheses[0];
 const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('guided'),[chatError,setChatError]=useState(''),[conversation,setConversation]=useState(false);
 const [events,setEvents]=useState<CaseEvent[]>([]),[storageError,setStorageError]=useState(''),[loading,setLoading]=useState(true),[saveBusy,setSaveBusy]=useState(false),[notice,setNotice]=useState('');
 const [evidence,setEvidence]=useState<Evidence|null>(null),[inspection,setInspection]=useState(false),[propose,setPropose]=useState(false),[settings,setSettings]=useState(false),[approved,setApproved]=useState(false),[draftFinding,setDraftFinding]=useState<Finding>('clear'),[note,setNote]=useState(''),[taskTitle,setTaskTitle]=useState(''),[proposal,setProposal]=useState<Proposal|null>(null);
 const [voiceAvailable,setVoiceAvailable]=useState(false),[listening,setListening]=useState(false),[voiceError,setVoiceError]=useState('');
 const [teamsReady,setTeamsReady]=useState(false),[teamsBusy,setTeamsBusy]=useState('');
 useEffect(()=>{fetch('/api/teams').then(r=>r.json() as Promise<{enabled:boolean}>).then(d=>setTeamsReady(d.enabled)).catch(()=>{});},[]);
 const generation=useRef(0),saveId=useRef(''),chatAbort=useRef<AbortController|null>(null),recognition=useRef<Recognition|null>(null),chatEnd=useRef<HTMLDivElement>(null);
 const changeScenario=(s:Scenario)=>{generation.current++;chatAbort.current?.abort();setBusy(false);setScenario(s);setFinding('none');setMessages([]);setChatError('');setNotice('');setInspection(false);setPropose(false);setEvidence(null);setConversation(false);setProposal(null);};
 useEffect(()=>{fetch('/api/copilot').then(r=>r.json() as Promise<{mode:string}>).then(d=>setMode(d.mode||'guided')).catch(()=>setMode('guided'));const w=window as typeof window&{SpeechRecognition?:unknown;webkitSpeechRecognition?:unknown};setVoiceAvailable(!!(w.SpeechRecognition||w.webkitSpeechRecognition));return()=>recognition.current?.stop();},[]);
 useEffect(()=>{let live=true;setLoading(true);setEvents([]);setStorageError('');fetch('/api/cases?scenario='+scenario).then(async r=>{const data=await r.json() as {error:string;events:CaseEvent[]};if(!r.ok)throw Error(data.error);if(live){setEvents(data.events);const last=data.events.filter(e=>e.kind==='finding').at(-1);setFinding(last?.body.finding||'none');}}).catch(e=>{if(live)setStorageError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false};},[scenario]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({block:'nearest'});},[messages,busy]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_pump_investigation',description:'Read the current synthetic pump evidence and hypothesis ranking. No equipment control or writes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');return {asset:'P-101',synthetic:true,revision:analysisRevision(result),evidence:result.evidence,hypotheses:result.hypotheses};}},{name:'select_demo_scenario',description:'Select a synthetic scenario and reset the unsaved conversation. Does not change plant equipment.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:scenarios.map(s=>s.id)}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {scenario:Scenario};if(saveBusy||!x||Object.keys(x).length!==1||!scenarios.some(s=>s.id===x.scenario))throw Error('Invalid scenario or save in progress');changeScenario(x.scenario);return {selected:x.scenario};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[scenario,result,saveBusy]);
 async function ask(text=question){if(!text.trim()||busy||loading)return;const token=generation.current;const controller=new AbortController();chatAbort.current=controller;setBusy(true);setConversation(true);setChatError('');setQuestion('');const next:Message[]=[...messages,{role:'user',content:text}];setMessages(next);try{const r=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario,finding,question:text,history:messages.slice(-8).map(({role,content})=>({role,content}))}),signal:controller.signal});const d=await r.json() as {error:string;reply:string;mode:string;trace:ToolTrace[];proposal?:Proposal};if(!r.ok)throw Error(d.error);if(token===generation.current){setMessages([...next,{role:'assistant',content:d.reply,mode:d.mode,trace:d.trace,proposal:d.proposal}]);if(d.mode==='agent')setMode('agent');}}catch(e){if(token===generation.current&&(e as Error).name!=='AbortError'){setChatError((e as Error).message);setQuestion(text);}}finally{if(token===generation.current)setBusy(false);}}
 function review(draft?:Proposal){try{const p=draft||proposalFor(result);if(p.revision!==analysisRevision(result)){setNotice('The case changed. Ask AQUA to prepare a fresh inspection.');return;}setProposal(p);setTaskTitle(p.title);setApproved(false);saveId.current='';setPropose(true);}catch{setNotice('No corrective inspection is supported. Preserve the baseline and continue routine checks.');}}
 function addFinding(){saveId.current='';setNote('');setDraftFinding(finding==='none'?'clear':finding);setInspection(true);}
 async function save(kind:'task'|'finding'){
  if(saveBusy)return;const token=generation.current,scope=scenario,selected=finding,draft=draftFinding;setSaveBusy(true);setStorageError('');
  try{if(!saveId.current)saveId.current=crypto.randomUUID();const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saveId.current,scenario:scope,kind,finding:kind==='finding'?draft:selected,note,title:taskTitle,approved,hypothesisId:proposal?.hypothesisId,revision:proposal?.revision})});const d=await r.json() as {error:string;event:CaseEvent};if(!r.ok)throw Error(d.error);const refreshed=await fetch('/api/cases?scenario='+scope);const list=await refreshed.json() as {error:string;events:CaseEvent[]};if(!refreshed.ok)throw Error(list.error);if(token!==generation.current)return;setEvents(list.events);if(kind==='finding'){setFinding(draft);generation.current++;chatAbort.current?.abort();setBusy(false);setMessages([]);setProposal(null);}setInspection(false);setPropose(false);setNotice(kind==='finding'?'Evidence saved. The hypothesis ranking has been reassessed.':'Approved task saved and read back: '+d.event.id.slice(0,8));saveId.current='';}
  catch(e){if(token===generation.current)setStorageError((e as Error).message);}finally{setSaveBusy(false);}
 }
 function voice(){if(listening){recognition.current?.stop();return;}const w=window as typeof window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const Engine=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Engine)return;const r=new Engine();recognition.current=r;r.lang='en-US';r.continuous=false;r.interimResults=false;r.onresult=e=>setQuestion(e.results[0][0].transcript);r.onerror=()=>{setVoiceError('Voice input was unavailable. You can type your question.');setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);setVoiceError('');}catch{setVoiceError('Voice input could not start.');}}
 async function sendTeams(id:string){if(teamsBusy)return;const token=generation.current,scope=scenario;setTeamsBusy(id);try{const response=await fetch('/api/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const data=await response.json() as {error?:string;message:string};if(!response.ok)throw Error(data.error||'Teams notification was not sent.');const history=await fetch('/api/cases?scenario='+scope);const saved=await history.json() as {events:CaseEvent[]};if(token===generation.current){if(history.ok)setEvents(saved.events);setNotice(data.message);}}catch(e){if(token===generation.current)setNotice((e as Error).message);}finally{setTeamsBusy('');}}
 function speak(text:string){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=1;speechSynthesis.speak(u);}}
 function exportCase(){const content={title:'AQUA P-101 investigation',synthetic:true,scenario,exportedAt:new Date().toISOString(),revision:analysisRevision(result),evidence:result.evidence,hypotheses:result.hypotheses,events,conversation:messages,limitations:['Illustrative scores, not calibrated probabilities','Remaining life not modelled','No live plant or external maintenance connection']};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='AQUA-P101-investigation.json';a.click();URL.revokeObjectURL(url);}
 const cite=(text:string)=>text.replace(/\*\*/g,'').split(/((?:SC|VB|MX|IN)-\d{2})/g).map((part,i)=>result.evidence.some(e=>e.id===part)?<button key={i} className="citation" onClick={()=>setEvidence(result.evidence.find(e=>e.id===part)!)}>{part}</button>:part);
 const trend=result.trend.slice(-Number(hours)),waveData=result.wave.samples.slice(0,512).map((value,i)=>({ms:i/result.wave.fs*1000,value}));
 const lastFinding=events.filter(e=>e.kind==='finding').at(-1);
 return <main className="operations-desk">
  <header className="station-bar"><a href="/" className="wordmark">AQUA</a><span className="station-label">WATER OPERATIONS</span><span className="station-location">STATION 03 / DUTY TRAIN 01</span><div className="header-actions"><span className="replay-label">SYNTHETIC REPLAY</span><button className="icon-button" aria-label="Connection status" onClick={()=>setSettings(true)}><Settings2 size={18}/></button></div></header>
  <section className="asset-masthead"><div><p className="eyebrow">ASSET RELIABILITY / PUMP INVESTIGATION</p><h1>P-101 <span>Main transfer pump</span></h1></div><dl className="equipment-strip"><div><dt>SPEED</dt><dd>1,500 rpm</dd></div><div><dt>MOTOR</dt><dd>110 kW</dd></div><div><dt>MODE</dt><dd>Duty / running</dd></div></dl><div className="scenario-picker"><label className="eyebrow">SIMULATION SCENARIO</label><Picker label="Simulation scenario" value={scenario} onChange={v=>changeScenario(v as Scenario)} items={scenarios} disabled={saveBusy}/></div></section>
  <div className="investigation-grid">
   <section className="plant-surface" aria-label="Pump train with instrument readings"><div className="section-heading"><h2>01 / PUMP TRAIN</h2><span>SCADA + VIBRATION + MAINTENANCE</span></div>
    <div className="schematic"><img src="/pump-train.svg" alt="Process flow from suction through the strainer and centrifugal pump to discharge; motor connects to the pump by shaft." className="pump-drawing"/><span className="drawing-label wetwell">FROM WET WELL</span><span className="drawing-label strainer">STRAINER</span><span className="drawing-label pump-name">P-101</span><span className="drawing-label motor-name">M-101 / DRIVE MOTOR</span><span className="drawing-label discharge">TO DISCHARGE HEADER</span>
     <button className="instrument suction" onClick={()=>setEvidence(result.evidence[0])}><span>PT-101 / SUCTION</span><strong>{result.now.suction.toFixed(2)} <small>bar(g)</small></strong></button>
     <button className="instrument flow" onClick={()=>setEvidence(result.evidence[1])}><span>FT-101 / FLOW</span><strong>{result.now.flow.toFixed(0)} <small>m³/h</small></strong></button>
     <button className="instrument vibration" onClick={()=>setEvidence(result.evidence[2])}><span>VB-101 / BEARING</span><strong>{result.quality?'INVALID':result.wave.rms.toFixed(2)} <small>{result.quality?'check sensor':'mm/s RMS'}</small></strong></button>
     <button className="instrument temperature" onClick={()=>setEvidence(result.evidence[1])}><span>TT-101 / BEARING</span><strong>{result.now.temp.toFixed(1)} <small>°C</small></strong></button>
     <button className="evidence-marker" onClick={()=>setEvidence(result.evidence[0])}>01 / Pressure evidence <ArrowRight size={14}/></button>
    </div>
    <div className="drawing-footnote"><span>MEASUREMENTS AT SOURCE</span><p>Select a reading to inspect the signal and its provenance.</p></div><div className="duty-strip"><span>HEAD <b>{result.head.toFixed(1)} m</b></span><span>WIRE-TO-WATER <b>{result.efficiency.toFixed(1)}%</b></span><small>Calculated from synthetic telemetry</small></div>
   </section>
   <aside className="case-dossier"><div className="section-heading"><span className="case-status">CASE 001 / {result.active?'OPEN':'BASELINE'}</span><span>{result.evidence.length} SOURCES</span></div><h2>{result.quality?'Can we trust this measurement?':scenario==='suction'?'Why is suction pressure falling on P-101?':scenario==='healthy'?'Is P-101 within its baseline?':'What is changing on P-101?'}</h2>
    <div className={'working-hypothesis '+(!result.active?'baseline':'')}><span className="eyebrow">{result.active?'WORKING HYPOTHESIS':'CURRENT ASSESSMENT'}</span><h3>{result.active?lead.title:'No strong fault evidence'}</h3><p>{result.active?`Support ${lead.support} / 100 · illustrative score`:'Continue routine checks and preserve the reference.'}</p></div>
    <h3 className="small-heading">Observed together</h3><ul className="evidence-list">{(result.quality?['VB-01','VB-02','SC-02']:lead.evidence.slice(0,3)).map((id,i)=><li key={id}><span>0{i+1}</span><button onClick={()=>setEvidence(result.evidence.find(e=>e.id===id)!)}>{result.evidence.find(e=>e.id===id)?.title} <b>{id}</b></button></li>)}</ul>
    <h3 className="small-heading">{finding!=='none'?'New evidence changes the case':'Still unresolved'}</h3><p className="uncertainty">{lead.against}</p>
    <button className="primary" onClick={addFinding} disabled={loading}><Plus size={16}/> Add inspection evidence</button><button className="text-button" onClick={()=>review()} disabled={loading||!result.active}>Review next inspection <ArrowRight size={14}/></button>
   </aside>
  </div>
  <Tabs value={tab} onValueChange={setTab} className="analysis-tray"><div className="analysis-navigation"><TabsList variant="line"><TabsTrigger value="trends">Trends</TabsTrigger><TabsTrigger value="spectrum">Spectrum</TabsTrigger><TabsTrigger value="waveform">Waveform</TabsTrigger><TabsTrigger value="fmea">FMEA</TabsTrigger><TabsTrigger value="history">Maintenance history</TabsTrigger></TabsList><button className="text-button" onClick={exportCase}><Download size={15}/> Export case</button></div>
   <TabsContent value="trends"><div className="analysis-grid"><section className="trend-pane"><div className="chart-controls"><Picker label="Trend signal" value={signal} onChange={setSignal} items={[{id:'suction',label:'Suction pressure / bar(g)'},{id:'vibration',label:'Vibration / mm/s RMS'},{id:'flow',label:'Flow / m³/h'},{id:'temp',label:'Bearing temperature / °C'}]}/><Picker label="Trend time window" value={hours} onChange={setHours} items={[{id:'24',label:'Last 24 hours'},{id:'48',label:'Last 48 hours'},{id:'72',label:'Last 72 hours'}]}/></div><div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{top:10,right:18,left:-14,bottom:0}}><CartesianGrid stroke="#dbe2e5" vertical={false}/><XAxis dataKey="hour" tickFormatter={v=>`−${72-Number(v)}h`} tickLine={false} axisLine={false} minTickGap={40}/><YAxis tickLine={false} axisLine={false} domain={['auto','auto']} tickFormatter={v=>Number(v).toFixed(signal==='flow'?0:1)}/><Tooltip {...tip} labelFormatter={v=>`${72-Number(v)} hours before snapshot`}/><Line dataKey={signal} stroke="#9b5700" strokeWidth={2.2} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="metadata">Hourly synthetic historian · matched speed · gaps remain visible</p></section><aside className="analysis-note"><p className="eyebrow">EVIDENCE, WITH LIMITS</p><h3>Three sources. One investigation.</h3><p>Correlating signals identifies a useful check. Confirmation needs independent inspection.</p><span className="metadata">RUL: not modelled / NPSH: not calculated</span></aside></div></TabsContent>
   {(['spectrum','waveform'] as const).map(view=><TabsContent key={view} value={view}><section className="signal-lab"><div className="lab-metrics"><span><b>{result.quality?'Withheld':result.wave.rms.toFixed(2)}</b> mm/s RMS</span><span><b>{result.quality?'—':result.wave.crest.toFixed(2)}</b> crest factor</span><span><b>{result.quality?'—':result.wave.kurtosis.toFixed(2)}</b> kurtosis</span><span><b>25 Hz</b> running speed</span></div>{result.quality?<div className="invalid-signal"><h3>Validate the measurement before diagnosis</h3><p>The channel is missing or mounting is reported loose. Derived waveform and spectral features are withheld.</p><button onClick={()=>setEvidence(result.evidence[2])}>Inspect VB-01</button></div>:<div className="lab-chart"><ResponsiveContainer width="100%" height="100%">{view==='spectrum'?<BarChart data={result.wave.spectrum.filter(x=>x.hz<=1000)} margin={{top:16,right:24,left:0,bottom:5}}><CartesianGrid stroke="#dbe2e5" vertical={false}/><XAxis dataKey="hz" type="number" domain={[0,1000]} ticks={[0,25,50,150,300,500,750,1000]} tickLine={false}/><YAxis tickLine={false}/><Tooltip {...tip} labelFormatter={v=>`${v} Hz`}/><ReferenceLine x={25} stroke="#175dab" strokeDasharray="3 3"/><ReferenceLine x={50} stroke="#9b5700" strokeDasharray="3 3"/><Bar dataKey="amplitude" fill="#175dab" isAnimationActive={false}/></BarChart>:<LineChart data={waveData} margin={{top:16,right:24,left:0,bottom:5}}><CartesianGrid stroke="#dbe2e5" vertical={false}/><XAxis dataKey="ms" type="number" domain={[0,250]} tickLine={false} tickFormatter={v=>Number(v).toFixed(0)}/><YAxis tickLine={false}/><Tooltip {...tip} labelFormatter={v=>`${Number(v).toFixed(1)} ms`}/><Line dataKey="value" stroke="#175dab" strokeWidth={1.2} dot={false} isAnimationActive={false}/></LineChart>}</ResponsiveContainer></div>}<p className="metadata">{view==='spectrum'?'Frequency / Hz · velocity amplitude / mm/s peak · Hann window · 1 Hz resolution':'Time / ms · velocity / mm/s · first 250 ms of one-second acquisition'} · synthetic signal</p></section></TabsContent>)}
   <TabsContent value="fmea"><section className="register"><div className="section-heading"><h2>Failure modes & evidence</h2><span>ILLUSTRATIVE S/O/D · ENGINEERING REVIEW REQUIRED</span></div><Table><TableHeader><TableRow><TableHead>Failure mode / support</TableHead><TableHead>Effect</TableHead><TableHead>Next check</TableHead><TableHead>S / O / D</TableHead><TableHead>RPN</TableHead></TableRow></TableHeader><TableBody>{result.hypotheses.map(h=><TableRow key={h.id}><TableCell><strong>{h.title}</strong><p>{h.support}/100 support</p><div className="chips">{h.evidence.map(id=><button key={id} onClick={()=>setEvidence(result.evidence.find(e=>e.id===id)!)}>{id}</button>)}</div></TableCell><TableCell>{h.effect}</TableCell><TableCell>{h.check}</TableCell><TableCell className="numeric">{h.severity} / {h.occurrence} / {h.detection}</TableCell><TableCell className="numeric">{h.severity*h.occurrence*h.detection}</TableCell></TableRow>)}</TableBody></Table><p className="metadata">These ratings illustrate the workflow. They are not calibrated failure probabilities or a confirmed root cause.</p></section></TabsContent>
   <TabsContent value="history"><section className="register"><div className="section-heading"><h2>Maintenance & case history</h2><span>{loading?'LOADING':events.length+' SAVED EVENTS'}</span></div><div className="history-list"><article><time>FEB 2021</time><div><h3>Commissioned into duty service</h3><p>110 kW motor · design flow 480 m³/h · synthetic asset record.</p></div></article><article><time>28 AUG 2026</time><div><h3>WO-2031 / Lubrication check</h3><p>No bearing replacement recorded. Suction strainer inspection is due.</p></div></article>{scenario==='alignment'&&<article><time>11 SEP 2026</time><div><h3>WO-2048 / Coupling replaced</h3><p>Alignment attachment is missing. Verify return-to-service evidence.</p></div></article>}{events.map(e=><article key={e.id}><time>{new Date(e.created).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}<small>{e.id.slice(0,8)}</small></time><div><h3>{e.kind==='task'?'Approved inspection task':findings.find(f=>f.id===e.body.finding)?.label}</h3><p>{e.body.title||e.body.note||'Reported finding saved and ranking reassessed.'}</p><small>{e.kind==='task'?'Saved in AQUA · no external work order issued':'Engineer-reported · synthetic case'}</small>{e.kind==='task'&&teamsReady&&<div className="teams-task-action">{e.body.teamsDelivery?<small>Teams: {e.body.teamsDelivery==='accepted'?'accepted by workflow':e.body.teamsDelivery==='pending'?'send attempted; check chat':e.body.teamsDelivery==='failed'?'workflow rejected notification':'delivery unconfirmed; check chat'}</small>:<button className="text-button" disabled={!!teamsBusy} onClick={()=>sendTeams(e.id)}>{teamsBusy===e.id?'Sending…':'Send to my Teams chat'}</button>}</div>}</div></article>)}</div>{storageError&&<p className="storage-note">{storageError} <a href="/signin-with-chatgpt?return_to=/desk" target="_top">Sign in to save</a></p>}</section></TabsContent>
  </Tabs>
  <form className="command-bar" onSubmit={e=>{e.preventDefault();ask();}}><label htmlFor="command">ASK AQUA</label><input id="command" value={question} maxLength={2000} placeholder="What evidence would change this diagnosis?" onChange={e=>setQuestion(e.target.value)}/><button type="button" className={listening?'listening':''} disabled={!voiceAvailable} onClick={voice} aria-label={listening?'Stop voice input':'Start voice input'}><Mic size={17}/><span>{listening?'Listening…':'Speak'}</span></button><button className="primary" disabled={busy||loading||!question.trim()}><Send size={16}/><span>{busy?'Working…':'Send'}</span></button><button type="button" aria-label="Open conversation" onClick={()=>setConversation(true)}><MessageSquare size={18}/></button><span className="command-mode">{mode==='guided'?'GUIDED DEMO':mode==='agent'?'AGENT VERIFIED':'AGENT CONFIGURED'}<small>{listening?'Review transcript before sending':'P-101 / current evidence'}</small></span></form>
  {voiceError&&<p className="voice-notice" role="status">{voiceError}</p>}
  <footer><span>AQUA / SIGNALSPROUT</span><span>{lastFinding?'Latest finding: '+findings.find(f=>f.id===lastFinding.body.finding)?.label:'Synthetic data · no plant controls'}</span><button onClick={()=>setSettings(true)}>Connection status</button></footer>
  {notice&&<div className="notice" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  <Sheet open={conversation} onOpenChange={setConversation}><SheetContent className="conversation-sheet"><SheetHeader><SheetTitle>Ask AQUA</SheetTitle><SheetDescription>{mode==='guided'?'Guided evidence rules · OpenRouter not connected':'Tool-using investigation agent · synthetic P-101 evidence'}</SheetDescription></SheetHeader><div className="conversation-body">{messages.length===0?<div className="conversation-intro"><h3>Start with a question.</h3><p>AQUA brings measurements, waveform features and maintenance history into one investigation.</p>{['Investigate why suction pressure is falling.','What evidence would change this diagnosis?','Propose the next inspection.','Explain the FMEA and remaining life.'].map(q=><button key={q} disabled={loading||busy} onClick={()=>ask(q)}>{q}<ArrowRight size={15}/></button>)}</div>:messages.map((m,i)=><article key={i} className={'message '+m.role}><div className="message-heading"><span>{m.role==='user'?'YOU':m.mode==='agent'?'AQUA / AGENT':'AQUA / GUIDED'}</span>{m.role==='assistant'&&<button aria-label="Read answer aloud" onClick={()=>speak(m.content)}><Volume2 size={16}/></button>}</div>{!!m.trace?.length&&<details className="tool-trace" open><summary>{m.trace.filter(t=>t.status==='complete').length} tools completed · {m.trace.filter(t=>t.status==='rejected').length} rejected</summary><ol>{m.trace.map((t,j)=><li key={j}><span className="mono">{t.name} / {t.status}</span><p>{t.summary} {t.evidence.map(id=><button key={id} className="citation" onClick={()=>setEvidence(result.evidence.find(e=>e.id===id)!)}>{id}</button>)}</p></li>)}</ol></details>}<p>{cite(m.content)}</p>{m.proposal&&<button className="primary" onClick={()=>review(m.proposal)}>Review proposed inspection <ArrowRight size={16}/></button>}</article>)}{busy&&<p className="agent-working" role="status">AQUA is selecting and running evidence tools…</p>}{chatError&&<p className="error" role="alert">{chatError}</p>}<div ref={chatEnd}/></div><form className="conversation-form" onSubmit={e=>{e.preventDefault();ask();}}><textarea aria-label="Ask the reliability agent" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a follow-up…" maxLength={2000}/><button className="primary" disabled={busy||loading||!question.trim()}>Send <ArrowRight size={16}/></button></form></SheetContent></Sheet>
  <Sheet open={!!evidence} onOpenChange={o=>{if(!o)setEvidence(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{evidence?.title}</SheetTitle><SheetDescription>{evidence?.id} / {evidence?.source}</SheetDescription></SheetHeader><div className="sheet-body"><p>{evidence?.detail}</p><h3>Quality & provenance</h3><p>{evidence?.quality}</p><h3>Interpretation boundary</h3><p>This item supports or challenges a hypothesis. Synthetic evidence demonstrates the process; it is not a validated prediction for a real pump.</p></div></SheetContent></Sheet>
  <Dialog open={inspection} onOpenChange={o=>{if(!saveBusy)setInspection(o);}}><DialogContent><DialogHeader><DialogTitle>A finding changes the case.</DialogTitle><DialogDescription>Record an inspection observation. The selected finding changes the evidence and hypothesis ranking.</DialogDescription></DialogHeader><label className="field-label">Inspection finding</label><Picker label="Inspection finding" value={draftFinding} onChange={v=>{setDraftFinding(v as Finding);saveId.current='';}} items={findings}/><p className="muted-copy">{findings.find(f=>f.id===draftFinding)?.description}</p><label htmlFor="note" className="field-label">Engineer note (optional)</label><textarea id="note" className="field" value={note} onChange={e=>{setNote(e.target.value);saveId.current='';}} placeholder="Measurement, location and check performed…" maxLength={2000}/><div className="revision-preview"><span>Leading hypothesis support</span><strong>{lead.support} → {analyse(scenario,draftFinding).hypotheses.find(h=>h.id===lead.id)?.support} <small>/ 100</small></strong><p>Illustrative support, not a probability. Notes are saved in the case record; the selected finding changes the analysis.</p></div>{storageError&&<p className="error" role="alert">{storageError} <a href="/signin-with-chatgpt?return_to=/desk" target="_top">Sign in to save</a></p>}<button className="primary" disabled={saveBusy} onClick={()=>save('finding')}>{saveBusy?'Saving…':'Save evidence & reassess'}</button></DialogContent></Dialog>
  <Dialog open={propose} onOpenChange={o=>{if(!saveBusy)setPropose(o);}}><DialogContent><DialogHeader><DialogTitle>Review the next inspection</DialogTitle><DialogDescription>Asset P-101 / destination: AQUA case tasks. No Maximo or Ambiguous work order will be issued.</DialogDescription></DialogHeader><label htmlFor="task" className="field-label">Inspection scope</label><textarea id="task" className="field" value={taskTitle} onChange={e=>{setTaskTitle(e.target.value);setApproved(false);saveId.current='';}} maxLength={500}/><div className="chips">{proposal?.evidence.map(id=><span key={id}>{id}</span>)}</div><p className="metadata">Evidence revision: {proposal?.revision}</p><label className="approval"><Checkbox checked={approved} onCheckedChange={v=>setApproved(v===true)}/>I reviewed the scope and approve saving this inspection task.</label>{storageError&&<p className="error" role="alert">{storageError} <a href="/signin-with-chatgpt?return_to=/desk" target="_top">Sign in to save</a></p>}<button className="primary" disabled={!approved||saveBusy||!taskTitle.trim()} onClick={()=>save('task')}>{saveBusy?'Saving and reading back…':'Approve & save inspection'}</button></DialogContent></Dialog>
  <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Connection status</SheetTitle><SheetDescription>What powers this investigation</SheetDescription></SheetHeader><div className="sheet-body"><h3>OpenRouter / {mode==='guided'?'not connected':mode==='agent'?'verified this session':'configured; awaiting a successful run'}</h3><p>{mode==='guided'?'Guided replies use explicit evidence rules. A server-side OpenRouter key enables free-form reasoning and evidence tool calls.':'The model selects allowlisted evidence tools and consumes their results. The trace shows actual tool execution; proposals require separate approval.'}</p><h3>SCADA, vibration and Maximo</h3><p>All plant measurements and maintenance records are synthetic. The application has no equipment-control connection.</p><h3>Case storage</h3><p>{storageError||'Engineer findings and approved AQUA tasks persist in the signed-in user’s case history.'}</p><h3>Voice</h3><p>Optional browser speech recognition fills a transcript for review before sending. Browser speech services may process audio online. Read-aloud uses the browser’s speech synthesis.</p><h3>Microsoft Teams</h3><p>{teamsReady?'Approved inspection tasks can be sent explicitly to your personal Teams demo chat from Maintenance history. The workflow receives an Adaptive Card; this is a notification connection, not a conversational Teams bot.':'Personal Teams notifications are not configured for this signed-in account.'}</p><h3>Hermes / Ambiguous AI</h3><p>Not connected. This version uses AQUA’s own bounded tool-calling loop and task history.</p><a href="https://www.figma.com/design/mMb88S1Lu81xu80SW13P7O?node-id=2-180" target="_blank" rel="noreferrer">View the Figma design</a></div></SheetContent></Sheet>
 </main>;
}
